name: Companion Module Checks

on:
  push:

jobs:
  check:
    name: Check module

    if: ${{ !contains(github.repository, 'companion-module-template-') }}

    permissions:
      packages: read

    uses: bitfocus/actions/.github/workflows/module-checks.yaml@6fca976b355200c8e6b05d888b1cd8109f3fa5c9 # main as of 2026-03-12
    # with:
    #   upload-artifact: true # uncomment this to upload the built package as an artifact to this workflow that you can download and share with others

